name: bug_busters
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  modal_progress_hud: ^0.1.3

  # Firebase
  # firebase_core: ^0.4.5
  firebase_core: ^0.5.3
  # firebase_auth: ^0.16.1
  firebase_auth: ^0.18.4+1
  # cloud_firestore: ^0.13.7
  cloud_firestore: ^0.14.4

  audioplayers: ^0.15.1
  http: ^0.12.2
  provider: ^4.3.1
  url_launcher: ^5.1.4
  # url_launcher_web: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: RogFont
      fonts:
        - asset: fonts/ROGFonts-Regular.otf
    - family: Aclonica
      fonts:
        - asset: fonts/Aclonica-Regular.ttf
